### ISSUE TITLE
A tag read consent state before a default was set

### ISSUE THREAD

**Issue by Rohaty** [Ayudante/gtm-consent-state#5]
Hey.

I downloaded the latest template (and created a variable from it) and when I check the Consent state, it shows me an error:

"A tag read consent state before a default was set".

![image](https://github.com/Ayudante/gtm-consent-state/assets/29813291/6e391aa6-c507-4ee3-80a6-ab6974e8e99d)

Shouldn't 'wait_for_update': 500 be added to 'consentTypesNames' ? After the addition, the error is no longer showing.

Then "consentTypesNames" would be like this:

const consentTypesNames = {
  defaultConsentTypesNames: {
    'ad_storage': 'ad_storage',
    'analytics_storage': 'analytics_storage',
    'functionality_storage': 'functionality_storage',
    'personalization_storage': 'personalization_storage',
    'security_storage': 'security_storage',
    'ad_user_data': 'ad_user_data',
    'ad_personalization': 'ad_personalization',
    'wait_for_update': 500
  },
  customConsentTypeName: {
    'custom': data.customName
  }
};

![image](https://github.com/Ayudante/gtm-consent-state/assets/29813291/9916f34e-8793-4d96-bbee-b4921ce57882)

Regards

**Comment by DaisakuHataoka** [comment]
Hi Rohaty.
Thanks for pointing this out!

I have checked the error message you pointed out.
After looking into it, the reason for this was that it "refers to the consent status before setting default status", i.e., the processing of the variable is running before the consent tool runs in "gtm.init_consent".

I have modified the template so that this error message does not occur.
However, in the sample you mentioned, the template process was stopped in the middle of the process by an error, so I am happy to report that the modification was made in a different way.

As a result, I modified the template so that it does not retrieve variables at "gtm.init_consent" event.
(This is because we realized that it makes no sense to get the consent status before the consent tool has been activated in the first place.)

Sorry for the delay in noticing this after you raised the Issue.
Thanks for pointing that out.
(This text is written with a translation tool, so I apologize if it is rude.)
